# Generated by Django 4.0.1 on 2022-01-13 05:23

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highlights',
            name='name',
            field=models.CharField(default=datetime.datetime(2022, 1, 13, 5, 23, 55, 706976, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
