# Generated by Django 4.0.1 on 2022-01-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_gallery_name_highlights_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlights',
            name='img',
            field=models.ImageField(upload_to='highlights/'),
        ),
    ]
