# Generated by Django 4.0.1 on 2022-01-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_highlights_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlights',
            name='name',
        ),
    ]
