# Generated by Django 4.0.1 on 2022-01-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_highlights_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='name',
        ),
    ]
